version: '3.7'

services:
  django_gunicorn:
    volumes:
      - ./media_volume:/app/mokuton/media
      - static_volume:/app/staticfiles
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - djangonetwork
    depends_on:
      - redis
    entrypoint: /app/docker/django/entrypoint.sh

  django_huey:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - djangonetwork
    depends_on:
      - redis
      - django_gunicorn
    entrypoint: /app/docker/huey/entrypoint.sh

  nginx:
    build: ./nginx
    volumes:
      - ./media_volume:/app/mokuton/media
      - static_volume:/app/staticfiles
    ports:
      - "8008:80"
    depends_on:
      - django_gunicorn
    networks:
      - djangonetwork

  redis:
    image: redis
    stdin_open: true
    tty: true
    networks:
      - djangonetwork

volumes:
  static_volume:

networks:
  djangonetwork:
    driver: bridge
