version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
