FROM python:3.8.5-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev \
    gcc python3-dev musl-dev jpeg-dev \
    zlib-dev libffi-dev cairo-dev pango-dev \
    gdk-pixbuf-dev openssl-dev cargo rust

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . /app

WORKDIR /app

COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "/entrypoint.sh"]
